name: Test Wallpaper Updater (Ubuntu)

on: [push]

jobs:
  test-wallpaper-updater:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install Dependancies via pip
      run: |
        sudo apt-get install python3-pip
        sudo apt-get install python3
        pip install requirements.txt
    - name: Run Wallpaper Updater Unit Test
      run: |
        python test_WallpaperUpdater.py


