name: Test Wallpaper Updater (Ubuntu)

on: [push]

jobs:
  test-wallpaper-updater:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
    - name: Install Dependancies via pip and apt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install dconf-cli
    - name: Run Wallpaper Updater Unit Test
      run: |
        python test_WallpaperUpdater.py


